### ISSUE TITLE
Overwriting event files at each write

### ISSUE THREAD

**Issue by chrisranderson** [chrisranderson/beholder#2]
See https://stackoverflow.com/questions/44893223/how-can-i-keep-only-one-summary-at-a-time-in-an-event-file.

**Comment by dandelionmane** [comment]
Why do you need to do this? Is this related to the other issue you posted about the tensor summary slowing down every write?

**Comment by chrisranderson** [comment]
One, because if I can only look at a frame at a time, then I only need to store a frame at a time, right? Since it's a live visualization, I always pictured a single frame always hanging around. The client requests a frame, the server grabs the current frame. The user's script writes the current frame at every train step. So far, this is proving pretty ugly, and what I'm doing now (a new event file at every train step) isn't the right way of doing things.

Two, to save on disk space. Looking at it now, for a very small network (20 train steps per second, ish) and a 600x800 image I think I would produce around .5 GB per minute, which isn't actually all that big. Most people probably won't have the same space restrictions I personally do, I'd guess, and probably have bigger networks that will run slower.

Right now, I find the current event file and make the accumulator process it whenever the client requests a frame. I was trying to get around the global timer set for reloading events. This seems nasty, so I'd love your thoughts. :sweat_smile:

**Comment by chrisranderson** [comment]
The relevant code is here: 

user script side: https://github.com/chrisranderson/beholder/blob/55cda875a5925ac530b0af467711c19ce795d642/beholder.py#L123-L137

server side: https://github.com/chrisranderson/beholder/blob/55cda875a5925ac530b0af467711c19ce795d642/beholder_plugin.py#L48-L68 and https://github.com/chrisranderson/beholder/blob/55cda875a5925ac530b0af467711c19ce795d642/beholder_plugin.py#L92-L93

**Comment by dandelionmane** [comment]
How about you use the summary API, but bypass the FileWriter (-> RecordWriter -> disk -> RecordReader -> Event File Loader) -> EventMultiplexer pipeline? That pipeline is pretty complex and is foundationally based on sets of assumptions that aren't relevant for your use case; append-only files (you want replace), storing history, stitching together many event files. It would be much simpler if you write a homebrew class that serializes the Summary proto yourself and reads from your own files.

**Comment by chrisranderson** [comment]
I think I had just assumed that was what I needed to go through - I've been trying to do things the TensorBoard way as much as possible. Thanks for the advice. This is way easier and cleaner. How does this look?

https://github.com/chrisranderson/beholder/blob/master/beholder.py#L85
https://github.com/chrisranderson/beholder/blob/master/beholder_plugin.py#L49

The repo is now in a state where I can request http://localhost:6006/data/plugin/beholder/beholder-frame.png and get a frame, and keep refreshing as the user script is running to get new frames. Making progress!

**Comment by dandelionmane** [comment]
Yeah, that approach seems simple and reasonable. Probably should be slightly more robust, e.g. logging exceptions and not catching all errors silently :) but fine for now

**Comment by chrisranderson** [comment]
@dandelionmane LOL. Yeah that's pretty bad. Great, thank you.
