### ISSUE TITLE
Handle broken pipe error

### ISSUE THREAD

**Issue by chrisranderson** [chrisranderson/beholder#22]
![image](https://user-images.githubusercontent.com/5461398/28184804-0bbc286a-67d2-11e7-8a2e-50c8f29b85f1.png)

**Comment by chrisranderson** [comment]
Not sure what caused this, but right now I can't reproduce it.

**Comment by jart** [comment]
Ignore that. It's probably caused by the browser closing the TCP client connection before the server was done sending. We haven't gotten around to suppressing that yet. It's kind of harmless.

**Comment by chrisranderson** [comment]
Okay, I'll close this. It might be related to how quickly I'm making requests.

**Comment by jart** [comment]
I don't think it's about speed. It's probably those PNG streamers. It seems to be an inherently persistent connection. The only way those things are going to get shut down is with a pipe error when the browser closes it, when navigating to a different page. If you can catch the error, I say just do it. Possibly by sending us a pull request.
