### ISSUE TITLE
Use perceptually uniform colormaps

### ISSUE THREAD

**Issue by chrisranderson** [chrisranderson/beholder#44]
See the explanation here: https://matplotlib.org/users/colormaps.html. They're also "relatively friendly to common forms of colorblindness" (see https://bids.github.io/colormap/).

Here's an example using the magma colormap (chosen by an informal survey of coworkers):
![image](https://user-images.githubusercontent.com/5461398/29093603-9856736e-7c47-11e7-8452-78db76261070.png)

Original style example:
![image](https://user-images.githubusercontent.com/5461398/29093642-c156fa22-7c47-11e7-872e-38a847773af1.png)

There's a bit of a slowdown in generating the image, but it's not terrible. For this small network, it was about .03 seconds. With all data shown, it was .75 seconds. For a big VGG network showing all data, it was a bit over 2 seconds (this is all on my laptop using the battery). I haven't timed slowdown across the entire pipeline, since images now have 2 additional channels.

Here's the code, where `*_data` is an array of shape [256, 3]:

```python
def apply_colormap(image, colormap='magma'):
  string_to_array = {
    'magma': _magma_data,
    'inferno': _inferno_data,
    'plasma': _plasma_data,
    'viridis': _viridis_data,
  }

  colormap_data = string_to_array[colormap]
  return (colormap_data[image]*255).astype(np.uint8)
```

@jart Do you think this should be the default? Thoughts in general?

**Comment by chrisranderson** [comment]
I can also add a select box that lets you choose which colormap to use.

**Comment by jart** [comment]
Paul Tol was just generous enough to design a new color-blind friendly color scheme, just for TensorBoard. @wchargin would be best to advise on this one.

**Comment by wchargin** [comment]
Paul's scheme is good for categorical data; @chrisranderson is right to use a perceptually uniform continuous colormap here instead.

But I don't see what's wrong with a simple grayscale color map. As long as you get the gamma parameter right, it's perfectly uniform (essentially definitionally so), and you don't have to worry about colorblindness at all.

What do you think?

A good tool for rough analysis of colorblind-friendliness is http://www.color-blindness.com/coblis-color-blindness-simulator/. (`magma` is okay.)

If you go with a select-box on the frontend, we have helpers for you to persist the state ([`tf-storage`](https://github.com/tensorflow/tensorboard/blob/5d0b9766ea6e7a879178a2e2b27c81bcdb117cf6/tensorboard/components/tf_storage/storage.ts) is the module; [here is an example use](https://github.com/tensorflow/tensorboard/blob/5d0b9766ea6e7a879178a2e2b27c81bcdb117cf6/tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html#L215)). We prefer the hash to local storage, though we support both.

**Comment by jart** [comment]
I guess the disadvantages of greyscale would be:

1. Black and white might not be the most aesthetically pleasing.
2. It's hard to tell black from dark grey apart. If most of your values falls in that lower end, that could be problematic. But if you make the lower end a different hue, you can easily perceive a greater range of values in total.

That matplotlib documentation page doesn't make a whole lot of sense to me, to be quite honest. Maybe we could use Matlab's color map. It seems legit:

![image](https://user-images.githubusercontent.com/49262/29100045-f16f02a2-7c5d-11e7-9442-71e9608355f9.png)

Source: https://bids.github.io/colormap/

They seem to have scripts that would help us adapt that color map to be incorporate or be complementary to TensorFlow orange, while maintaining all those properties.

*However* I'm noticing that these fancy color scales seem confusing for images with low pixel density, like row 7 in the screenshot above. I wouldn't be able to make sense of that visualization by itself. Fancy color scales seem to work best, to me, when the pixels have roughly the same width and height.

Should the color scale be adapted depending on the shape? If so, how would a legend be displayed showing how the hues map to values?

**Comment by jart** [comment]
Having read into things more, here's the analysis of the magma color map:

![image](https://user-images.githubusercontent.com/49262/29100596-4b21e12c-7c61-11e7-880f-9e2bfd529560.png)

I think this was actually a good choice. I like that it works on a black and white printer. It seems to allow me to perceive a greater range of values, versus the original black and white. It *almost* seems to be aesthetically harmonious with TensorFlow orange.

I have some reservations about the purple, but I think there's a couple people I can reach out to for feedback.

**Comment by chrisranderson** [comment]
Huh, I hadn't considered finding a grayscale one. Part of it, like @jart (I don't know when to use Justine or your username in these conversations) mentioned is aesthetics.

> It's hard to tell black from dark grey apart. If most of your values falls in that lower end, that could be problematic.

From one perspective, that's exactly what you want, as long as everything is uniform. If it isn't uniform, your perception of the relative differences between values is skewed I think([nice stackexchange answer on the topic](https://stats.stackexchange.com/questions/223315/why-use-colormap-viridis-over-jet)).

If your goal isn't to get an accurate picture, and it's to see detail in the image, maybe we could try histogram equalization or taking the log of the data before scaling it to [0, 255] or something. That would be easy to try.

**Comment by jart** [comment]
You can address me by my initials, first name, or last name. Whichever you prefer :)

**Comment by chrisranderson** [comment]
Ha. Perfect, thanks. Okay... original image: 
![image](https://user-images.githubusercontent.com/5461398/29101091-46d69e94-7c6d-11e7-8def-56c5389063a1.png)

Values shifted upward and `np.log`ed before being scaled:
![image](https://user-images.githubusercontent.com/5461398/29101069-22157882-7c6d-11e7-9720-549d95da5897.png)

Used `cv2.equalizeHist` after the sections were scaled:
![image](https://user-images.githubusercontent.com/5461398/29101072-2e053100-7c6d-11e7-8ee1-4e2ea9bf800c.png)

These can get a little intense when used with a colormap:
![image](https://user-images.githubusercontent.com/5461398/29101204-da0c4ea2-7c6d-11e7-9b3b-ec53a5244184.png)

**Comment by jart** [comment]
My advice would be to just do it. I think magma is absolutely a step in the right direction. The analysis looks good. We can fine tune it later. Once again, great thinking.

**Comment by jart** [comment]
By the way, be sure to add a color map legend to the side bar if you do this.

**Comment by chrisranderson** [comment]
I actually already pushed magma as the default, but I can add a legend (#45).
