### ISSUE TITLE
Can't build tensorboard_x

### ISSUE THREAD

**Issue by ted-kapustin** [chrisranderson/beholder#59]
I am following the installation & build procedure described in README.md. When I run the command:

bazel build beholder/tensorboard_x

I have a lot of errors:

[fedora-IT2251705 beholder]$ bazel build beholder/tensorboard_x
Starting local Bazel server and connecting to it...
ERROR: /home/<user>/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/stylesheets/closure_css_binary.bzl:65:13: name 'set' is not defined
ERROR: /home/<user>/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/testing/phantomjs_test.bzl:31:10: name 'set' is not defined
ERROR: /home/<user>/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/webfiles/web_library.bzl:43:14: name 'set' is not defined
ERROR: /home/<user>/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/stylesheets/closure_css_library.bzl:27:13: name 'set' is not defined
ERROR: /home/<user>/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/filegroup_external.bzl:23:16: name 'set' is not defined
ERROR: /home/<user>/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/compiler/closure_js_library.bzl:142:26: name 'set' is not defined
ERROR: /home/<user>n/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl:44:13: name 'set' is not defined
ERROR: /home/<user>/.cache/bazel/_bazel_<user>/c50acbba45f1b3bce0cf1fb12b59253d/external/io_bazel_rules_closure/closure/compiler/closure_js_binary.bzl:220:13: name 'set' is not defined
ERROR: error loading package '': Extension 'closure/stylesheets/closure_css_binary.bzl' has errors
ERROR: error loading package '': Extension 'closure/stylesheets/closure_css_binary.bzl' has errors
INFO: Elapsed time: 0.342s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Any clue what is wrong?

**Comment by chrisranderson** [comment]
This is in tensorboard nightly, maybe in tensorboard these days :) this repo is old, the Tensorflow folks are in charge of it now, sorry. Check the Tensorboard repo for more info on how to use Beholder.

**Comment by ted-kapustin** [comment]
Another question (not issue): is it possible to run a custom tensorboard (for example, tensorboard_x that comes with Beholder plugin) WITHOUT Bazel? I want to deploy/distribute my future plugin & custom tensorboard, but I don't want to make its users install Bazel and C++ compiler. Will the users have to build their tensorboards from my code in order to use my plugin? Somehow this topic is not covered anywhere, including https://github.com/tensorflow/tensorboard-plugin-example

**Comment by chrisranderson** [comment]
You shouldn't use this repository at all. Beholder might even ship with TensorFlow now. I'm pretty sure you can pip install tb-nightly or something like that to use Beholder. I'd recommend checking the TensorBoard repo.

**Comment by chrisranderson** [comment]
Ohhh gotcha. Yeah When I did this a year ago it was pretty difficult for others to use my plugin. They would have to build all of TensorBoard using Bazel and use TensorFlow nightly. Which is painful.

It could be that the third-party plugin ecosystem is more user-friendly nowadays, I'm not sure. @jart can you provide an update?
